"""Shared data contracts for pitch tracking."""

from .types import (
    Detection,
    Frame,
    PitchMetrics,
    RayObservation,
    StereoObservation,
    TrajectoryFit,
    TrajectoryInput,
    TrackSample,
)
from .tooling import (
    AlignmentAnalysisRequest,
    AlignmentAnalysisResult,
    CalibrationRequest,
    CalibrationResult,
    EnvironmentValidationResult,
    PhysicalValidationRequest,
    PhysicalValidationResult,
    TrainingReportRequest,
    TrainingReportResult,
)
from .setup import (
    CalibrationQualityReport,
    CoarseRectificationResult,
    ExposureLockResult,
    FocusLockResult,
    StereoCalibrationProfile,
    StereoOverlapResult,
    SyncCheckResult,
)
from .catalog import (
    CameraCapabilities,
    CameraCatalogEntry,
    CameraMode,
    KnownDevice,
    KnownGoodSettings,
)
from .capability_observation import (
    ALL_CONTROLS,
    CapabilityObservation,
    ControlQueryResult,
    ControlQueryStatus,
    build_simulated_observation,
)
from .evidence import (
    AssociationEdgeEvidence,
    Candidate2DEvidence,
    CandidateDecisionEvidence,
    DecisionArtifactBindings,
    Observation3DEvidence,
    PairingOutcomeEvidence,
    PitchVerdictEvidence,
    StereoMatchEvidence,
    TriangulationDecisionEvidence,
)
from .quality import (
    CorrectionRecord,
    MeasurementEvidence,
    MeasurementStatus,
    QualityAssessment,
    QUALITY_DEGRADED,
    QUALITY_ESTIMATED,
    QUALITY_REJECTED,
    QUALITY_UNAVAILABLE,
    QUALITY_VALIDATED,
)
from .physical_validation import (
    ApprovalSignatureV2,
    PhysicalValidationCaseV2,
    PhysicalValidationDatasetV2,
    PhysicalValidationProtocolV2,
    ReferenceChannelV2,
    TailErrorPolicyV2,
    TrajectoryModeApprovalV2,
)
from .setup_snapshot import (
    SETUP_SNAPSHOT_SCHEMA,
    SetupSnapshotAssessment,
    SetupSystemSnapshot,
    assess_setup_snapshot_payload,
)
from .setup_capture import SetupCaptureResult
from .durable_registry import DURABLE_CONTRACTS, DurableContractSpec, validate_durable_contracts

__all__ = [
    "Detection",
    "Frame",
    "PitchMetrics",
    "RayObservation",
    "StereoObservation",
    "TrajectoryFit",
    "TrajectoryInput",
    "TrackSample",
    "AlignmentAnalysisRequest",
    "AlignmentAnalysisResult",
    "CalibrationRequest",
    "CalibrationResult",
    "EnvironmentValidationResult",
    "PhysicalValidationRequest",
    "PhysicalValidationResult",
    "TrainingReportRequest",
    "TrainingReportResult",
    "SyncCheckResult",
    "FocusLockResult",
    "ExposureLockResult",
    "StereoOverlapResult",
    "CoarseRectificationResult",
    "StereoCalibrationProfile",
    "CalibrationQualityReport",
    "CameraMode",
    "CameraCapabilities",
    "KnownGoodSettings",
    "CameraCatalogEntry",
    "KnownDevice",
    "ALL_CONTROLS",
    "CapabilityObservation",
    "ControlQueryResult",
    "ControlQueryStatus",
    "build_simulated_observation",
    "Candidate2DEvidence",
    "CandidateDecisionEvidence",
    "DecisionArtifactBindings",
    "PairingOutcomeEvidence",
    "AssociationEdgeEvidence",
    "TriangulationDecisionEvidence",
    "StereoMatchEvidence",
    "Observation3DEvidence",
    "PitchVerdictEvidence",
    "CorrectionRecord",
    "MeasurementEvidence",
    "MeasurementStatus",
    "QualityAssessment",
    "QUALITY_DEGRADED",
    "QUALITY_ESTIMATED",
    "QUALITY_REJECTED",
    "QUALITY_UNAVAILABLE",
    "QUALITY_VALIDATED",
    "ApprovalSignatureV2",
    "PhysicalValidationCaseV2",
    "PhysicalValidationDatasetV2",
    "PhysicalValidationProtocolV2",
    "ReferenceChannelV2",
    "TailErrorPolicyV2",
    "TrajectoryModeApprovalV2",
    "SETUP_SNAPSHOT_SCHEMA",
    "SetupSnapshotAssessment",
    "SetupSystemSnapshot",
    "assess_setup_snapshot_payload",
    "SetupCaptureResult",
    "DURABLE_CONTRACTS",
    "DurableContractSpec",
    "validate_durable_contracts",
]
